примерное содержание проекта:

*   машина, которая определяет инфекционное заболевание по симптоматике (классификатор, машинное обучение + предобработка данных это пандас)
- мне не нужна машина мне нужна просто таблица и косинусная близость по симптомам
*   парсер который анализирует словарь с симптомами на предмет совпадений с текстом или что-то в этом духе (NLP-инструмент для русского языка)

0.   исправление опечаток +
1.   лемматизатор (симптомы) и удаление стоп-слов чтобы распарсить текст+
3.   еще можно по приколу добавить парсинг языка (чтобы он умел говорить "я умею работать только с русским языком)


*   бот который может выдать какую-то информацию о заболевании на основании запроса (БД и запросы sql); нужно еще чтобы он мог что-то неточное разобрать (типа хдлера вместо холера) *действительно хд*

In [135]:
complaint = input()

Пациент испытывает боль в мышцах и суставах, есть ослабление мышц; в анамнез имели место половые внебрачные крнтакты, но сифилис исключен по аналрзам

Установка пакетов

In [ ]:
!pip install deep_translator
!pip install autocorrect -q
!pip install -U spacy --q
!python -m spacy download ru_core_news_sm --q
!pip install nltk
!pip install pymorphy3 --q
!pip install gensim sentence-transformers

Импорты (все нужные)

In [ ]:
#обработка и перевод таблицы
import pandas as pd
from deep_translator import GoogleTranslator

#обработка вводимого текста
from autocorrect import Speller
import spacy
import nltk

from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

from nltk.corpus import stopwords
nltk.download('stopwords')

nlp_ru = spacy.load("ru_core_news_sm")

from sklearn.metrics.pairwise import cosine_similarity
#from sklearn.feature_extraction.text import CountVectorizer

###Работа с таблицей

In [111]:
df_symptoms = pd.read_csv('DiseaseAndSymptoms.csv')

In [112]:
df_symptoms.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Шаг 0: переводим таблицу, потому что она будет работать с русским языком

In [7]:
translator = GoogleTranslator(source='en', target='ru')

In [116]:
unique_values = pd.Series(df_symptoms.values.ravel()).dropna().unique().tolist()
unique_values_2 = {}

for value in unique_values:
    new_value = value.replace('_', ' ').lstrip()
    unique_values_2[value] = new_value

df_symptoms = df_symptoms.replace(unique_values_2)

value_set = set(unique_values_2.values())

def translate_text(text):
    if pd.notna(text) and isinstance(text, str):
        return translator.translate(text)

trans_dict = {}

for value in value_set:
    trans_dict[value] = translate_text(value)

{'swelling of stomach': 'вздутие живота', 'Migraine': 'Мигрень', 'constipation': 'запор', 'dehydration': 'обезвоживание', 'Arthritis': 'Артрит', 'Fungal infection': 'Грибковая инфекция', 'Dimorphic hemmorhoids(piles)': 'Диморфные геморроидальные узлы (сваи)', 'scurring': 'несущийся', 'AIDS': 'СПИД', 'red spots over body': 'красные пятна по телу', 'lethargy': 'вялость', 'runny nose': 'насморк', 'Paralysis (brain hemorrhage)': 'Паралич (кровоизлияние в мозг)', 'blurred and distorted vision': 'затуманенное и искаженное зрение', 'silver like dusting': 'серебро, как пыль', 'fatigue': 'усталость', 'back pain': 'боль в спине', 'skin rash': 'кожная сыпь', 'pain behind the eyes': 'боль за глазами', 'depression': 'депрессия', 'muscle pain': 'мышечная боль', 'Diabetes ': 'Диабет', 'Osteoarthristis': 'Остеоартрис', 'puffy face and eyes': 'опухшее лицо и глаза', 'skin peeling': 'шелушение кожи', 'muscle weakness': 'мышечная слабость', 'pus filled pimples': 'прыщи, наполненные гноем', 'receiving blood transfusion': 'получение переливания крови', 'drying and tingling lips': 'сохнут и покалывают губы', 'coma': 'кома', 'continuous sneezing': 'непрерывное чихание', 'loss of balance': 'потеря равновесия', 'brittle nails': 'ломкие ногти', 'Gastroenteritis': 'Гастроэнтерит', 'painful walking': 'болезненная ходьба', 'Tuberculosis': 'Туберкулез', 'spotting  urination': 'кровянистые выделения при мочеиспускании', 'Cervical spondylosis': 'Шейный спондилез', 'unsteadiness': 'неустойчивость', 'bladder discomfort': 'дискомфорт в мочевом пузыре', 'Hypertension ': 'Гипертония', 'Peptic ulcer diseae': 'Язвенная болезнь желудка', 'Hepatitis B': 'Гепатит Б', 'fluid overload': 'перегрузка жидкостью', 'Hepatitis E': 'Гепатит Е', 'swollen extremeties': 'опухшие крайности', 'Hypothyroidism': 'Гипотиреоз', 'mild fever': 'легкая лихорадка', 'throat irritation': 'раздражение горла', 'malaise': 'недомогание', 'blackheads': 'угри', 'cough': 'кашель', 'slurred speech': 'невнятная речь', 'blood in sputum': 'кровь в мокроте', 'itching': 'зуд', 'belly pain': 'боль в животе', 'sunken eyes': 'запавшие глаза', 'family history': 'семейная история', 'hepatitis A': 'гепатит А', 'diarrhoea': 'диарея', 'Jaundice': 'Желтуха', 'yellowing of eyes': 'пожелтение глаз', 'patches in throat': 'пятна в горле', 'acute liver failure': 'острая печеночная недостаточность', 'Varicose veins': 'Варикозное расширение вен', 'Acne': 'Прыщи', 'weakness of one body side': 'слабость одной стороны тела', 'Impetigo': 'Импетиго', 'distention of abdomen': 'вздутие живота', 'rusty sputum': 'ржавая мокрота', 'vomiting': 'рвота', 'loss of appetite': 'потеря аппетита', 'excessive hunger': 'чрезмерный голод', 'phlegm': 'мокрота', 'weight loss': 'потеря веса', 'knee pain': 'боль в колене', 'swelling joints': 'опухшие суставы', 'shivering': 'дрожь', 'bruising': 'синяки', 'Common Cold': 'Простуда', 'fast heart rate': 'быстрый сердечный ритм', 'abdominal pain': 'боль в животе', 'dischromic  patches': 'дисхромные пятна', 'weight gain': 'увеличение веса', 'watering from eyes': 'слезоточивость из глаз', 'Chronic cholestasis': 'Хронический холестаз', 'stomach bleeding': 'желудочное кровотечение', 'pain in anal region': 'боль в анальной области', 'neck pain': 'боль в шее', 'mood swings': 'перепады настроения', 'enlarged thyroid': 'увеличенная щитовидная железа', 'Typhoid': 'тифозный', 'toxic look (typhos)': 'токсичный вид (тиф)', 'inflammatory nails': 'воспаленные ногти', 'red sore around nose': 'красная болячка вокруг носа', 'Psoriasis': 'Псориаз', 'sweating': 'потливость', 'Dengue': 'Денге', 'prominent veins on calf': 'выступающие вены на икрах', 'passage of gases': 'прохождение газов', 'redness of eyes': 'покраснение глаз', 'palpitations': 'сердцебиение', 'swollen blood vessels': 'опухшие кровеносные сосуды', 'cold hands and feets': 'холодные руки и ноги', 'polyuria': 'полиурия', 'Chicken pox': 'Ветряная оспа', 'irregular sugar level': 'нерегулярный уровень сахара', 'joint pain': 'боль в суставах', 'Hypoglycemia': 'Гипогликемия', 'movement stiffness': 'скованность движений', 'visual disturbances': 'нарушения зрения', 'Drug Reaction': 'Реакция на лекарство', 'cramps': 'судороги', 'yellowish skin': 'желтоватая кожа', 'stiff neck': 'скованность мышц шеи', 'restlessness': 'беспокойство', 'altered sensorium': 'измененная сенсорика', 'mucoid sputum': 'слизистая мокрота', 'swelled lymph nodes': 'опухшие лимфатические узлы', 'weakness in limbs': 'слабость в конечностях', 'loss of smell': 'потеря обоняния', 'sinus pressure': 'синусовое давление', 'Pneumonia': 'Пневмония', 'blister': 'волдырь', 'extra marital contacts': 'внебрачные контакты', 'bloody stool': 'кровавый стул', 'Hyperthyroidism': 'Гипертиреоз', 'chills': 'озноб', 'dark urine': 'темная моча', 'anxiety': 'беспокойство', 'muscle wasting': 'атрофия мышц', 'yellow crust ooze': 'желтая корка слизь', 'irritation in anus': 'раздражение в анусе', '(vertigo) Paroymsal  Positional Vertigo': '(головокружение) Пароймсальное позиционное головокружение', 'Hepatitis C': 'Гепатит С', 'Heart attack': 'Острое сердечно-сосудистое заболевание', 'acidity': 'кислотность', 'ulcers on tongue': 'язвы на языке', 'swollen legs': 'опухшие ноги', 'small dents in nails': 'небольшие вмятины на ногтях', 'stomach pain': 'боль в животе', 'hip joint pain': 'боль в тазобедренном суставе', 'nodal skin eruptions': 'узловые высыпания на коже', 'breathlessness': 'одышка', 'headache': 'головная боль', 'high fever': 'высокая температура', 'increased appetite': 'повышенный аппетит', 'foul smell of urine': 'неприятный запах мочи', 'continuous feel of urine': 'постоянное ощущение мочи', 'Bronchial Asthma': 'Бронхиальная астма', 'Alcoholic hepatitis': 'Алкогольный гепатит', 'internal itching': 'внутренний зуд', 'pain during bowel movements': 'боль во время дефекации', 'nausea': 'тошнота', 'dizziness': 'головокружение', 'Urinary tract infection': 'Инфекция мочевыводящих путей', 'chest pain': 'боль в груди', 'Malaria': 'Малярия', 'yellow urine': 'желтая моча', 'abnormal menstruation': 'аномальная менструация', 'obesity': 'ожирение', 'burning micturition': 'жгучее мочеиспускание', 'receiving unsterile injections': 'получение нестерильных инъекций', 'GERD': 'ГЭРБ', 'irritability': 'раздражительность', 'spinning movements': 'вращательные движения', 'lack of concentration': 'отсутствие концентрации', 'congestion': 'скопление', 'Allergy': 'Аллергия', 'history of alcohol consumption': 'история употребления алкоголя', 'Hepatitis D': 'Гепатит Д', 'indigestion': 'несварение желудка'}

In [117]:
df_symptoms = df_symptoms.replace(trans_dict)

Шаг 1: сделать из этого табличку со списком симптомов

In [158]:
df_symptoms['symptoms_list'] = df_symptoms.drop('Disease', axis=1).values.tolist()
df_symptoms['symptoms_list'] = df_symptoms['symptoms_list'].apply(lambda x: [i for i in x if pd.notna(i)])
df_symptoms = df_symptoms[['Disease', 'symptoms_list']]
df_symptoms['symptoms_list'] = df_symptoms['symptoms_list'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)
df_symptoms

/tmp/ipykernel_1492/3206944067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_symptoms['symptoms_list'] = df_symptoms.drop('Disease', axis=1).values.tolist()
/tmp/ipykernel_1492/3206944067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_symptoms['symptoms_list'] = df_symptoms['symptoms_list'].apply(lambda x: [i for i in x if pd.notna(i)])

,Disease,symptoms_list
0,Грибковая инфекция,зуд кожная сыпь узловые высыпания на коже дисх...
1,Грибковая инфекция,кожная сыпь узловые высыпания на коже дисхромн...
2,Грибковая инфекция,зуд узловые высыпания на коже дисхромные пятна
3,Грибковая инфекция,зуд кожная сыпь дисхромные пятна
4,Грибковая инфекция,зуд кожная сыпь узловые высыпания на коже
...,...,...
4915,(головокружение) Пароймсальное позиционное гол...,рвота головная боль тошнота вращательные движе...
4916,Прыщи,"кожная сыпь прыщи, наполненные гноем угри несу..."
4917,Инфекция мочевыводящих путей,жгучее мочеиспускание дискомфорт в мочевом пуз...
4918,Псориаз,кожная сыпь боль в суставах шелушение кожи сер...
4919,Импетиго,кожная сыпь высокая температура волдырь красна...

In [159]:
all_symptoms = list(set([symptoms for symptoms
                         in df_symptoms['symptoms_list']]))

###Парсинг текста

Идея бота состоит в том, что он принимает на вход цельный врачебный анализ жалобы пациента, а не дает ему шаблон или выбор из нескольких кнопок: это позволяет (*позволяло бы, если бы речь шла о настоящем медицинском проекте*) не упустить ничего, что показалось значимым врачу и о чем мог не подумать разработчик. А мне позволяет использовать NLP-инструменты:)

####Исправление опечаток

Текст вводится живым человеком, поэтому опечатки, очевидно, могут быть – вряд ли они будут в ключевых словах, но всякий случай бот умеет с этим справляться; если, например, врач выберет кнопку "Я хочу узнать о лечении и профилактике диагноза" и случайно напишет туда слово "Хдлера", бот не поймет, что тот пытался сказать, и скажет, что такой болезни у него нет – а с дополнительной проверкой он сразу выдаст результат.

In [140]:
spell = Speller(lang='ru')

dictionary for this language not found, downloading...
__________________________________________________
couldn't download http://ipfs.io/ipfs/QmbRSZvfJV6zN12zzWhecphcvE9ZBeQdAJGQ9c9ttJXzcg/ru.tar.gz, trying next url...
__________________________________________________
couldn't download https://gateway.pinata.cloud/ipfs/QmbRSZvfJV6zN12zzWhecphcvE9ZBeQdAJGQ9c9ttJXzcg/ru.tar.gz, trying next url...
__________________________________________________
couldn't download https://cf-ipfs.com/ipfs/QmbRSZvfJV6zN12zzWhecphcvE9ZBeQdAJGQ9c9ttJXzcg/ru.tar.gz, trying next url...
__________________________________________________
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
done!

In [141]:
complaint = spell(complaint)

####Подготовка текста

In [22]:
sw = stopwords.words('russian')
sw.extend(['жаловаться', 'начаться', 'появиться', 'пациент', 'симптом'])

#добавлены слова, которые идейно должны встречаться в большом количестве сообщений

In [146]:
complaint_doc = nlp_ru(complaint)
complaint_tokens = set([token.lemma_ for token in complaint_doc])
words = [w.lower() for w in word_tokenize(' '.join(complaint_tokens),
                                          language='russian') if w.isalpha()]
#issues конечно есть с этим isalpha, он не распарсит "поднялась 37.8"
complaint_filtered = [w for w in words if w not in sw]

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [149]:
print(complaint_filtered)

['анализ', 'половой', 'контакт', 'иметь', 'исключить', 'боль', 'мышца', 'испытывать', 'внебрачный', 'сустав', 'место', 'ослабление', 'сифилис', 'анамнез']

In [29]:
!pip install gensim nltk

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 14.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [154]:
texts = [' '.join(complaint_filtered)] + all_symptoms

In [129]:
print(texts[:5])

['сустав казаться температура лихорадка серьёзный боль', 'атрофия мышц пятна в горле внебрачные контакты', 'головная боль боль в груди головокружение потеря равновесия', 'головная боль боль в груди головокружение потеря равновесия отсутствие концентрации', 'кислотность несварение желудка головная боль затуманенное и искаженное зрение чрезмерный голод скованность мышц шеи депрессия раздражительность нарушения зрения']

In [153]:
complaint_filtered

['анализ',
 'половой',
 'контакт',
 'иметь',
 'исключить',
 'боль',
 'мышца',
 'испытывать',
 'внебрачный',
 'сустав',
 'место',
 'ослабление',
 'сифилис',
 'анамнез']

In [33]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import gensim.downloader as api
from gensim.models import KeyedVectors

!wget https://rusvectores.org/static/models/rusvectores4/RNC/ruscorpora_upos_skipgram_300_5_2018.vec.gz
model = KeyedVectors.load_word2vec_format('ruscorpora_upos_skipgram_300_5_2018.vec.gz')

--2026-03-25 18:25:41--  https://rusvectores.org/static/models/rusvectores4/RNC/ruscorpora_upos_skipgram_300_5_2018.vec.gz
Resolving rusvectores.org (rusvectores.org)... 129.240.189.200, 2001:700:112::200
Connecting to rusvectores.org (rusvectores.org)|129.240.189.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 199864398 (191M) [application/x-gzip]
Saving to: ‘ruscorpora_upos_skipgram_300_5_2018.vec.gz’

ruscorpora_upos_ski 100%[===================>] 190.61M  25.3MB/s    in 8.4s

2026-03-25 18:25:50 (22.7 MB/s) - ‘ruscorpora_upos_skipgram_300_5_2018.vec.gz’ saved [199864398/199864398]

In [34]:
from pymorphy3 import MorphAnalyzer

morph = MorphAnalyzer()

In [161]:
tagged_list = [[f'{morph.parse(word)[0].normal_form}_{morph.parse(word)[0].tag.POS}'
                for word in list_.split(' ')]
               for list_ in texts]

In [156]:
def get_sentence_vector(text):
    #words = text.split()
    vectors = [model[word] for word in text if word in model]
    return np.mean(vectors, axis=0) if vectors else np.zeros(300)

vec = np.array([get_sentence_vector(text) for text in tagged_list])

target = vec[0].reshape(1, -1)
others = vec[1:]
similarities = cosine_similarity(target, others).flatten()
sorted_indices = np.argsort(similarities)[::-1]

disease_pred = texts[sorted_indices[0] + 1]
print(disease_pred)

атрофия мышц пятна в горле высокая температура внебрачные контакты

In [157]:
df_symptoms.loc[df_symptoms['symptoms_list'] == disease_pred, 'Disease'].iloc[0]

'СПИД'

###БД

Этот раздел может использоваться, если пользователь говорит "я хочу узнать больше о заболевании".

In [180]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('diseases.db')

conn.execute('DROP TABLE IF EXISTS diseases')
conn.execute('DROP TABLE IF EXISTS symptoms')

df_diseases = pd.DataFrame({
    'id': range(1, len(df_symptoms['Disease'].unique()) + 1),
    'name': df_symptoms['Disease'].unique()
})
df_diseases.to_sql('diseases', conn, if_exists='replace', index=False)

df_symptoms_new = pd.DataFrame({
    'id': range(1, len(df_symptoms) + 1),
    'symptoms_list': df_symptoms['symptoms_list']
})
df_symptoms_new.to_sql('symptoms', conn, if_exists='replace', index=False);

In [187]:
cursor = conn.cursor()
cursor.execute('''
    CREATE TABLE IF NOT EXISTS icd_who (
        disease_id INTEGER,
        mkb_link TEXT
    )
''')

df_diseases = pd.read_sql('SELECT * FROM diseases', conn)
df_mkb = pd.read_excel('/content/SimpleTabulation-ICD-11-MMS-ru.xlsx')

for idx, row in df_diseases.iterrows():
    disease_name = row['name']
    disease_id = row['id']

    match = df_mkb[df_mkb['Title'].str.contains(disease_name, case=False, na=False)]

    if not match.empty:
        cursor.execute('''
            INSERT OR REPLACE INTO icd_who (disease_id, disease_name, mkb_link)
            VALUES (?, ?, ?)
        ''', (disease_id, disease_name, match.iloc[0]['Parent']))
        conn.commit()

/tmp/ipykernel_1492/3646869670.py:16: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  match = df_mkb[df_mkb['Title'].str.contains(disease_name, case=False, na=False)]

In [ ]:
cursor.execute('''
    CREATE TABLE IF NOT EXISTS prevention (
        disease_id INTEGER,
        prevention_cautions TEXT
    )
''')
df_diseases = pd.read_sql('SELECT * FROM diseases', conn)

for _, row in df_diseases.iterrows():
    cursor.execute('''
        INSERT OR REPLACE INTO prevention (disease_id, disease_name, prevention_measures)
        VALUES (?, ?, ?)
    ''', (row['id'], row['name'], 'Пока нет информации'))

conn.commit()

In [ ]:
conn.close()

###Бот

этот раздел катастрофически не закончен

In [2]:
!pip install pyTelegramBotAPI

Collecting pyTelegramBotAPI
  Downloading pytelegrambotapi-4.32.0-py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pyTelegramBotAPI) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pyTelegramBotAPI) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pyTelegramBotAPI) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pyTelegramBotAPI) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pyTelegramBotAPI) (2026.2.25)
Downloading pytelegrambotapi-4.32.0-py3-none-any.whl (303 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.3/303.3 kB 8.2 MB/s eta 0:00:00
Installing collected packages: pyTelegramBotAPI
Successfully installed pyTelegramBotAPI-4.32.0

In [3]:
!pip install aiogram nest_asyncio

Collecting aiogram
  Downloading aiogram-3.26.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: aiofiles<26.0,>=23.2.1 in /usr/local/lib/python3.12/dist-packages (from aiogram) (24.1.0)
Requirement already satisfied: aiohttp<3.14,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from aiogram) (3.13.3)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.12/dist-packages (from aiogram) (2026.2.25)
Collecting magic-filter<1.1,>=1.0.12 (from aiogram)
  Downloading magic_filter-1.0.12-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: pydantic<2.13,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from aiogram) (2.12.3)
Requirement already satisfied: typing-extensions<=5.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from aiogram) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<3.14,>=3.9.0->aiogram) (1.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<2.13,>=2.4.1->aiogram) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<2.13,>=2.4.1->aiogram) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<2.13,>=2.4.1->aiogram) (0.4.2)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp<3.14,>=3.9.0->aiogram) (3.11)
Downloading aiogram-3.26.0-py3-none-any.whl (716 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 716.4/716.4 kB 9.0 MB/s eta 0:00:00
Downloading magic_filter-1.0.12-py3-none-any.whl (11 kB)
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 447, in run
    conflicts = self._determine_conflicts(to_install)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 578, in _determine_conflicts
    return check_install_conflicts(to_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 42, in create_package_set_from_installed
    dependencies = list(dist.iter_dependencies())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_dists.py", line 222, in iter_dependencies
    req = Requirement(req_string.strip())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 124, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 151, in _parse_requirement_marker
    marker = _parse_marker(tokenizer)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 266, in _parse_marker
    expression = [_parse_marker_atom(tokenizer)]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 291, in _parse_marker_atom
    marker = _parse_marker_item(tokenizer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 305, in _parse_marker_item
    marker_var_right = _parse_marker_var(tokenizer)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 317, in _parse_marker_var
    return process_python_str(tokenizer.read().text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/packaging/_parser.py", line 332, in process_python_str
    value = ast.literal_eval(python_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 66, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 216, in exc_logging_wrapper
    logger.debug("Exception information:", exc_info=True)
  File "/usr/lib/python3.12/logging/__init__.py", line 1527, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/lib/python3.12/logging/handlers.py", line 75, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1280, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 112, in format
    formatted = super().format(record)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 711, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 661, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.12/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/traceback.py", line 733, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/traceback.py", line 418, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
                                                     ^^^^^^^^^
  File "/usr/lib/python3.12/traceback.py", line 355, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/traceback.py", line 369, in _get_code_position
    return next(itertools.islice(positions_gen, instruction_index // 2, None))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^C

KeyboardInterrupt:

In [ ]:
import telebot
from telebot.async_telebot import AsyncTeleBot
from telebot import types

In [ ]:
!pip install aiogram nest_asyncio

from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
import nest_asyncio

nest_asyncio.apply()

TOKEN = '8334838059:AAE1goQ36xVP_rMaoV_K2DFs_PRk2dLFsc4'
bot = Bot(token=TOKEN)
dp = Dispatcher()

@dp.message(Command('start'))
async def start(message: types.Message):
    # Новый способ создания клавиатуры
    keyboard = [
        [types.KeyboardButton(text="Начать работу")]
    ]
    markup = types.ReplyKeyboardMarkup(keyboard=keyboard, resize_keyboard=True)
    await message.answer('Нажмите "Начать работу"', reply_markup=markup)

@dp.message()
async def handle(message: types.Message):
    if message.text == "Начать работу":
        keyboard = [
            [types.KeyboardButton(text="Я согласен с условиями")]
        ]
        markup = types.ReplyKeyboardMarkup(keyboard=keyboard, resize_keyboard=True)
        await message.answer(
"""Здравствуйте! Я – бот-помощник в определении инфекционных заболеваний.
Пожалуйста, перед использованием ознакомьтесь с несколькими правилами:
- я предназначен только для врачебного пользования; если вы не врач, к сожалению, вы не можете воспользоваться мной.
- я не могу дать точный диагноз, а могу лишь подтвердить опасения или дать перечень симптомов заболевания;
окончательное решение о диагнозе остается за вами!
Нажимая кнопку "Я согласен с условиями", вы подтверждаете, что являетесь врачом с медицинским образованием и прочитали условия выше.""", reply_markup=markup)

    elif message.text == "Я согласен с условиями":
        keyboard = [
            [types.KeyboardButton(text="Я не знаю диагноз пациента и хочу определить его по жалобам")],
            [types.KeyboardButton(text="Я предполагаю, что знаю диагноз, и хочу его подтвердить")],
            [types.KeyboardButton(text="Я просто хочу узнать больше о конкретном заболевании")]
        ]
        markup = types.ReplyKeyboardMarkup(keyboard=keyboard, resize_keyboard=True)
        await message.answer("Выберите, пожалуйста, нужное действие", reply_markup=markup)

In [ ]:
await dp.start_polling(bot)